package com.speedyg.btw.team;

import com.speedyg.btw.messages.Messages;
/**
 * This enum created for Basic Team Wars plugin.
 *
 * @author Ozgen, Yusuf Serhat
 * @version 1.0.0-ALFA
 * @since 18.12.2019
 */

public enum Permission {

    ENEMY_FRIEND_TEAM_CONTROL(new PermissionLoader(Messages.TEAM_CONTROL_NAME, Messages.TEAM_CONTROL_DESCRIPTION)),
    BALANCE_CONTROL(new PermissionLoader(Messages.BALANCE_CONTROL_NAME, Messages.BALANCE_CONTROL_DESCRIPTION)),
    CHANGE_SPAWN_POINT(new PermissionLoader(Messages.SPAWN_CONTROL_NAME, Messages.SPAWN_CONTROL_DESCRIPTION)),
    CHANGE_TEAM_LOGO(new PermissionLoader(Messages.LOGO_CONTROL_NAME, Messages.LOGO_CONTROL_DESCRIPTION)),
    CHANGE_TEAM_NAME(new PermissionLoader(Messages.CHANGE_TEAM_NAME_NAME, Messages.CHANGE_TEAM_NAME_DESCRIPTION)),
    CHANGE_TEAM_SIZE(new PermissionLoader(Messages.CHANGE_TEAM_SIZE_NAME, Messages.CHANGE_TEAM_SIZE_DESCRIPTION)),
    CLAIM_OPTIONS(new PermissionLoader(Messages.CHANGE_CLAIM_OPTIONS_NAME, Messages.CHANGE_CLAIM_OPTIONS_DESCRIPTION)),
    MEMBER_OPTIONS(new PermissionLoader(Messages.CHANGE_MEMBER_OPTIONS_NAME, Messages.CHANGE_MEMBER_OPTIONS_DESCRIPTION)),
    WAR_OPTIONS(new PermissionLoader(Messages.CHANGE_WAR_OPTIONS_NAME, Messages.CHANGE_WAR_OPTIONS_DESCRIPTION)),
    ADD_FUND_TEAM(new PermissionLoader(Messages.AND_FUND_TEAM_NAME, Messages.ADD_FUND_TEAM_DESCRIPTION)),
    WITHDRAW_FUND_TEAM(new PermissionLoader(Messages.WITHDRAW_FUND_TEAM_NAME, Messages.WITHDRAW_FUND_TEAM_DESCRIPTION)),
    CHANGE_SPAWN_POINT_MEMBER(new PermissionLoader(Messages.CHANGE_SPAWN_POINT_MEMBER_NAME, Messages.CHANGE_SPAWN_POINT_MEMBER_DESCRIPTION)),
    CHANGE_SPAWN_POINT_MODERATOR(new PermissionLoader(Messages.CHANGE_SPAWN_POINT_MOD_NAME, Messages.CHANGE_SPAWN_POINT_MOD_DESCRIPTION)),
    CHANGE_SPAWN_POINT_ADMIN(new PermissionLoader(Messages.CHANGE_SPAWN_POINT_ADMIN_NAME, Messages.CHANGE_SPAWN_POINT_ADMIN_DESCRIPTION)),
    CHECK_TEAM_JOIN_REQUESTS(new PermissionLoader(Messages.CHECK_TEAM_JOIN_REQUESTS_NAME, Messages.CHECK_TEAM_JOIN_REQUESTS_DESCRIPTION)),
    CHANGE_MEMBER_OPTIONS(new PermissionLoader(Messages.PERMISSION_CHANGE_MEMBER_OPTIONS_NAME, Messages.PERMISSION_CHANGE_MEMBER_OPTIONS_DESCRIPTION)),
    CHANGE_MODERATOR_OPTIONS(new PermissionLoader(Messages.PERMISSION_CHANGE_MOD_OPTIONS_NAME, Messages.PERMISSION_CHANGE_MOD_OPTIONS_DESCRIPTION)),
    CHANGE_ADMIN_OPTIONS(new PermissionLoader(Messages.PERMISSION_CHANGE_ADMIN_OPTIONS_NAME, Messages.PERMISSION_CHANGE_ADMIN_OPTIONS_DESCRIPTION)),
    ACCEPT_TEAMJOIN_REQUESTS(new PermissionLoader(Messages.ACCEPT_TEAMJOIN_REQUESTS_NAME, Messages.ACCEPT_TEAMJOIN_REQUESTS_DESCRIPTION)),
    REJECT_TEAMJOIN_REQUESTS(new PermissionLoader(Messages.REJECT_TEAMJOIN_REQUESTS_NAME, Messages.REJECT_TEAMJOIN_REQUESTS_DESCRIPTION)),
    CHANGE_MEMBERS_PERMISSIONS(new PermissionLoader(Messages.CHANGE_MEMBERS_PERMISSIONS_NAME, Messages.CHANGE_MEMBERS_PERMISSIONS_DESCRIPTION)),
    PROMOTE_MODERATOR_PERMISSION(new PermissionLoader(Messages.PROMOTE_MODERATOR_PERMISSION_NAME, Messages.PROMOTE_MODERATOR_PERMISSION_DESCRIPTION)),
    KICK_PLAYER(new PermissionLoader(Messages.KICK_PLAYER_NAME, Messages.KICK_PLAYER_DESCRIPTION)),
    CHANGE_PLAYERS_SELF_PERMISSIONS(new PermissionLoader(Messages.CHANGE_PLAYERS_SELF_PERMISSIONS_NAME, Messages.CHANGE_PLAYERS_SELF_PERMISSIONS_DESCRIPTION)),
    CHANGE_MODS_PERMISSIONS(new PermissionLoader(Messages.CHANGE_MODS_PERMISSIONS_NAME, Messages.CHANGE_MODS_PERMISSIONS_DESCRIPTION)),
    PROMOTE_ADMIN_PERMISSION(new PermissionLoader(Messages.PROMOTE_ADMIN_PERMISSION_NAME, Messages.PROMOTE_ADMIN_PERMISSION_DESCRIPTION)),
    DEGRADE_MOD_TO_PLAYER_PERMISSION(new PermissionLoader(Messages.DEGRADE_MOD_TO_PLAYER_PERMISSION_NAME, Messages.DEGRADE_MOD_TO_PLAYER_PERMISSION_DESCRIPTION)),
    DEGRADE_ADMIN_TO_MOD_PERMISSION(new PermissionLoader(Messages.DEGRADE_ADMIN_TO_MOD_PERMISSION_NAME, Messages.DEGRADE_ADMIN_TO_MOD_PERMISSION_DESCRIPTION)),
    CHANGE_ADMINS_PERMISSIONS(new PermissionLoader(Messages.CHANGE_ADMINS_PERMISSIONS_NAME, Messages.CHANGE_ADMINS_PERMISSIONS_DESCRIPTION)),
    CHECK_FRIEND_TEAMS(new PermissionLoader(Messages.CHECK_FRIEND_TEAMS_NAME, Messages.CHECK_FRIEND_TEAMS_DESCRIPTION)),
    CHECK_ENEMY_TEAMS(new PermissionLoader(Messages.CHECK_ENEMY_TEAMS_NAME, Messages.CHECK_ENEMY_TEAMS_DESCRIPTION)),
    CHECK_AND_CONTROL_TEAM_REL_REQUESTS(new PermissionLoader(Messages.CHECK_AND_CONTROL_TEAM_REL_REQUESTS_NAME, Messages.CHECK_AND_CONTROL_TEAM_REL_REQUESTS_DESCRIPTION)),
    CHECK_NEUTRAL_TEAMS(new PermissionLoader(Messages.CHECK_NEUTRAL_TEAMS_NAME, Messages.CHECK_NEUTRAL_TEAMS_DESCRIPTION)),
    REMOVE_FRIEND_TEAM(new PermissionLoader(Messages.REMOVE_FRIEND_TEAM_NAME, Messages.REMOVE_FRIEND_TEAM_DESCRIPTION)),
    REMOVE_ENEMY_TEAM(new PermissionLoader(Messages.REMOVE_ENEMY_TEAM_NAME, Messages.REMOVE_ENEMY_TEAM_DESCRIPTION)),
    SEND_FRIEND_TEAM_REQUEST(new PermissionLoader(Messages.SEND_FRIEND_TEAM_REQUEST_NAME, Messages.SEND_FRIEND_TEAM_REQUEST_DESCRIPTION)),
    ADD_ENEMY_TEAM(new PermissionLoader(Messages.ADD_ENEMY_TEAM_NAME, Messages.ADD_ENEMY_TEAM_DESCRIPTION)),
    ACCEPT_TEAM_FRIEND_REQUESTS(new PermissionLoader(Messages.ACCEPT_TEAM_FRIEND_REQUESTS_NAME, Messages.ACCEPT_TEAM_FRIEND_REQUESTS_DESCRIPTION)),
    REJECT_TEAM_FRIEND_REQUESTS(new PermissionLoader(Messages.REJECT_TEAM_FRIEND_REQUESTS_NAME, Messages.REJECT_TEAM_FRIEND_REQUESTS_DESCRIPTION)),
    CHECK_MESSAGE_BOX(new PermissionLoader(Messages.CHECK_MESSAGE_BOX_NAME, Messages.CHECK_MESSAGE_BOX_DESCRIPTION)),
    READ_TEAM_MESSAGES(new PermissionLoader(Messages.READ_TEAM_MESSAGES_NAME, Messages.READ_TEAM_MESSAGES_DESCRIPTION)),
    MARK_AS_READ(new PermissionLoader(Messages.MARK_AS_READ_NAME, Messages.MARK_AS_READ_DESCRIPTION)),
    REMOVE_TEAM_MESSAGES(new PermissionLoader(Messages.REMOVE_TEAM_MESSAGES_NAME, Messages.REMOVE_TEAM_MESSAGES_DESCRIPTION)),
    CLEAR_ALL_MESSAGES_OF_TEAM(new PermissionLoader(Messages.CLEAR_ALL_MESSAGES_OF_TEAM_NAME, Messages.CLEAR_ALL_MESSAGES_OF_TEAM_DESCRIPTION)),
    CLEAR_READ_MESSAGES_OF_TEAM(new PermissionLoader(Messages.CLEAR_READ_MESSAGES_OF_TEAM_NAME, Messages.CLEAR_READ_MESSAGES_OF_TEAM_DESCRIPTION)),
    MARK_MESSAGES_READ(new PermissionLoader(Messages.MARK_MESSAGES_READ_NAME, Messages.MARK_MESSAGES_READ_DESCRIPTION)),
    TAKE_NEW_CLAIM(new PermissionLoader(Messages.TAKE_NEW_CLAIM_NAME, Messages.TAKE_NEW_CLAIM_DESCRIPTION)),
    TELEPORT_CLAIMS(new PermissionLoader(Messages.TELEPORT_CLAIMS_NAME, Messages.TELEPORT_CLAIMS_DESCRIPTION)),
    BLOCK_BREAK_CLAIMS(new PermissionLoader(Messages.BLOCK_BREAK_CLAIMS_NAME, Messages.BLOCK_BREAK_CLAIMS_DESCRIPTION)),
    BLOCK_PLACE_CLAIMS(new PermissionLoader(Messages.BLOCK_PLACE_CLAIMS_NAME, Messages.BLOCK_PLACE_CLAIMS_DESCRIPTION)),
    USE_CHEST_IN_CLAIMS(new PermissionLoader(Messages.USE_CHEST_IN_CLAIMS_NAME, Messages.USE_CHEST_IN_CLAIMS_DESCRIPTION)),
    USE_ENDER_CHEST_IN_CLAIMS(new PermissionLoader(Messages.USE_ENDER_CHEST_IN_CLAIMS_NAME, Messages.USE_ENDER_CHEST_IN_CLAIMS_DESCRIPTION)),
    USE_TNT_IN_CLAIMS(new PermissionLoader(Messages.USE_TNT_IN_CLAIMS_NAME, Messages.USE_TNT_IN_CLAIMS_DESCRIPTION)),
    USE_HOPPER_IN_CLAIMS(new PermissionLoader(Messages.USE_HOPPER_IN_CLAIMS_NAME, Messages.USE_HOPPER_IN_CLAIMS_DESCRIPTION)),
    USE_FLINT_AND_STEEL_IN_CLAIMS(new PermissionLoader(Messages.USE_FLINT_AND_STEEL_IN_CLAIMS_NAME, Messages.USE_FLINT_AND_STEEL_IN_CLAIMS_DESCRIPTION)),
    USE_WORKBENCH_IN_CLAIMS(new PermissionLoader(Messages.USE_WORKBENCH_IN_CLAIMS_NAME, Messages.USE_WORKBENCH_IN_CLAIMS_DESCRIPTION)),
    USE_ENCHANTMENT_TABLE_IN_CLAIMS(new PermissionLoader(Messages.USE_ENCHANTMENT_TABLE_IN_CLAIMS_NAME, Messages.USE_ENCHANTMENT_TABLE_IN_CLAIMS_DESCRIPTION)),
    USE_FURNACE_IN_CLAIMS(new PermissionLoader(Messages.USE_FURNACE_IN_CLAIMS_NAME, Messages.USE_FURNACE_IN_CLAIMS_DESCRIPTION)),
    USE_BREWING_STAND_IN_CLAIMS(new PermissionLoader(Messages.USE_BREWING_STAND_IN_CLAIMS_NAME, Messages.USE_BREWING_STAND_IN_CLAIMS_DESCRIPTION)),
    USE_ARMOR_STAND_IN_CLAIMS(new PermissionLoader(Messages.USE_ARMOR_STAND_IN_CLAIMS_NAME, Messages.USE_ARMOR_STAND_IN_CLAIMS_DESCRIPTION)),
    USE_BED_IN_CLAIMS(new PermissionLoader(Messages.USE_BED_IN_CLAIMS_NAME, Messages.USE_BED_IN_CLAIMS_DESCRIPTION)),
    USE_ENDER_PEARL_IN_CLAIMS(new PermissionLoader(Messages.USE_ENDER_PEARL_IN_CLAIMS_NAME, Messages.USE_ENDER_PEARL_IN_CLAIMS_DESCRIPTION)),
    USE_LAVA_IN_CLAIMS(new PermissionLoader(Messages.USE_LAVA_IN_CLAIMS_NAME, Messages.USE_LAVA_IN_CLAIMS_DESCRIPTION)),
    USE_MOB_SPAWNER_IN_CLAIMS(new PermissionLoader(Messages.USE_MOB_SPAWNER_IN_CLAIMS_NAME, Messages.USE_MOB_SPAWNER_IN_CLAIMS_DESCRIPTION)),
    USE_FISHING_ROD_IN_CLAIMS(new PermissionLoader(Messages.USE_FISHING_ROD_IN_CLAIMS_NAME, Messages.USE_FISHING_ROD_IN_CLAIMS_DESCRIPTION)),
    USE_MINECART_IN_CLAIMS(new PermissionLoader(Messages.USE_MINECART_IN_CLAIMS_NAME, Messages.USE_MINECART_IN_CLAIMS_DESCRIPTION)),
    USE_WATER_IN_CLAIMS(new PermissionLoader(Messages.USE_WATER_IN_CLAIMS_NAME, Messages.USE_WATER_IN_CLAIMS_DESCRIPTION)),
    DROP_ITEM_IN_CLAIM(new PermissionLoader(Messages.DROP_ITEM_IN_CLAIM_NAME, Messages.DROP_ITEM_IN_CLAIM_DESCRIPTION)),
    CHANGE_TEAM_DESCRIPTION(new PermissionLoader(Messages.CHANGE_TEAM_DESCRIPTION_NAME, Messages.CHANGE_TEAM_DESCRIPTION_DESCRIPTION)),
    CHANGE_TEAM_SHORT_NAME(new PermissionLoader(Messages.CHANGE_TEAM_SHORT_NAME_NAME, Messages.CHANGE_TEAM_SHORT_NAME_DESCRIPTION)),
    REMOVE_CLAIM(new PermissionLoader(Messages.REMOVE_CLAIM_NAME, Messages.REMOVE_CLAIM_DESCRIPTION)),
    OPEN_AUTO_BUILD_CLAIM_MENU(new PermissionLoader(Messages.OPEN_AUTO_BUILD_CLAIM_MENU_NAME, Messages.OPEN_AUTO_BUILD_CLAIM_MENU_DESCRIPTION)),
    BUILD_A_SCHEMATIC_FOR_CLAIM(new PermissionLoader(Messages.BUILD_A_SCHEMATIC_FOR_CLAIM_NAME, Messages.BUILD_A_SCHEMATIC_FOR_CLAIM_DESCRIPTION)),
    START_NEW_SIEGE(new PermissionLoader(Messages.START_NEW_SIEGE_NAME, Messages.START_NEW_SIEGE_DESCRIPTION)),
    SET_WARRIORS_OF_TEAM(new PermissionLoader(Messages.SET_WARRIORS_OF_TEAM_NAME, Messages.SET_WARRIORS_OF_TEAM_DESCRIPTION)),
    SELECT_WAR_KITS(new PermissionLoader(Messages.SELECT_WAR_KITS_NAME, Messages.SELECT_WAR_KITS_DESCRIPTION));
    private PermissionLoader loader;

    Permission(PermissionLoader loader) {
        this.loader = loader;
    }

    public PermissionLoader getPermissionLoader() {
        return this.loader;
    }

    @Override
    public String toString() {
        return this.name().toLowerCase();
    }


}
